#!/bin/bash

echo "🎾 LIVE TENNIS BETTING - QUICK SETUP"
echo "===================================="
echo ""
echo "Step 1: Get FREE API key"
echo "------------------------"
echo "Visit: https://the-odds-api.com/"
echo "- Sign up (free)"
echo "- Get API key (500 requests/month free)"
echo ""
echo "Step 2: Set your API key"
echo "------------------------"
echo "Run ONE of these commands:"
echo ""
echo "Option A - Environment variable (temporary):"
echo "  export ODDS_API_KEY='your_key_here'"
echo ""
echo "Option B - Add to your shell profile (permanent):"
echo "  echo 'export ODDS_API_KEY=\"your_key_here\"' >> ~/.zshrc"
echo "  source ~/.zshrc"
echo ""
echo "Step 3: Run the analyzer"
echo "------------------------"
echo "  python live_betting_analyzer.py"
echo ""
echo "What you get:"
echo "✓ Real live matches (ATP/WTA)"
echo "✓ Odds from 30+ bookmakers (Bet365, Pinnacle, etc.)"
echo "✓ Best odds highlighted"
echo "✓ Markov probability analysis"
echo "✓ Edge calculations"
echo "✓ Betting recommendations"
echo ""
echo "===================================="
